// <auto-generated />
using FlipCoin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlipCoin.Migrations
{
    [DbContext(typeof(CoinContext))]
    [Migration("20220725053928_CoinMigration")]
    partial class CoinMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FlipCoin.Models.Toss", b =>
                {
                    b.Property<int>("toss")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("toss"), 1L, 1);

                    b.Property<string>("Down")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Up")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("toss");

                    b.ToTable("Coins");
                });
#pragma warning restore 612, 618
        }
    }
}
