// <auto-generated />
using Coin_flip.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coin_flip.Migrations
{
    [DbContext(typeof(Data))]
    [Migration("20220725095521_CoinContext")]
    partial class CoinContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Coin_flip.Models.CoinDataBase", b =>
                {
                    b.Property<int>("Toss")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Toss"), 1L, 1);

                    b.Property<string>("Down")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Up")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Toss");

                    b.ToTable("Coins");
                });
#pragma warning restore 612, 618
        }
    }
}
