using DataStructure;
Stack stack = new Stack();
stack.Push(1);
stack.Push(5);
stack.Push(10);
int value=stack.Pop();
Console.WriteLine(value);
int value1=stack.Pop();
Console.WriteLine(value1);
int value2=stack.Pop();
Console.WriteLine(value2);
int value3 = stack.Pop();
Console.WriteLine(value3);